### ISSUE TITLE
Seeing AirflowException("Use keyword arguments when initializing operators")

### ISSUE THREAD

**Issue by johnlawlor-tomtom** [panovvv/airflow-livy-plugins#8]
I am using airflow-livy-operators 0.4.2 and apache-airflow 2.1.2. When I use the LivyBatchOperator, it makes a call to the LivyBatchSensor, which calls its initializer without `batch_id` as a keyword argument.

```
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow_livy/batch.py", line 179, in execute
    LivyBatchSensor(
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 138, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
```

**Comment by sapkos** [comment]
@panovvv I created a PR that should fix this issue, please take a look https://github.com/panovvv/airflow-livy-operators/pull/9

**Comment by vpanovk** [comment]
Thank you! Merging...
